version: '3.8'

services:
  app:
    image: maden:latest
    ports:
      - "8080:8080"
    depends_on:
      - etcd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  etcd:
    image: quay.io/coreos/etcd:v3.4.15
    ports:
      - "2379:2379"
      - "2380:2380"
    command:
      - /usr/local/bin/etcd
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-client-urls
      - http://0.0.0.0:2379