// Code generated by MockGen. DO NOT EDIT.
// Source: maden/pkg/scheduler (interfaces: Scheduler)

// Package mocks is a generated GoMock package.
package mocks

import (
	shared "maden/pkg/shared"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockScheduler is a mock of Scheduler interface.
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler.
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance.
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// SchedulePod mocks base method.
func (m *MockScheduler) SchedulePod(arg0 *shared.Pod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchedulePod", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SchedulePod indicates an expected call of SchedulePod.
func (mr *MockSchedulerMockRecorder) SchedulePod(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchedulePod", reflect.TypeOf((*MockScheduler)(nil).SchedulePod), arg0)
}
