version: api/v1
kind: Deployment
spec:
  name: example-deployment
  replicas: 1
  selector:
    app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: example:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer