version: api/v1
kind: Deployment
spec:
  name: example-dep1
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: my-minimal-image
        ports:
        - containerPort: 800
      restartPolicy: Always
---
apiVersion: v1
kind: Service
spec:
  name: example-service3
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 82
  type: LoadBalancer