version: api/v1
kind: Deployment
spec:
  name: example-dep1
  replicas: 2
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: my-minimal-image
        ports:
        - containerPort: 800
      restartPolicy: Always
---
apiVersion: v1
kind: Service
spec:
  name: example-service5
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 81
      targetPort: 82
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
spec:
  name: example-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: example-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
spec:
  name: example-pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi