version: api/v1
kind: Deployment
spec:
  name: example-deployment-test-pod-52
  replicas: 5
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: my-minimal-image
        ports:
        - containerPort: 800
---
apiVersion: v1
kind: Service
spec:
  name: example-service3
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 82
  type: LoadBalancer